# PR workflow.
#
# Runs full suite of checks, with warnings treated as errors.
# Gather code coverage stats and publish them on coveralls.io.

name: Merge Version Change PRs automatically

on: pull_request

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Merge Version change PR
      uses: ridedott/merge-me-action@master
      with:
        GITHUB_LOGIN: MaidSafe-QA
        GITHUB_TOKEN: ${{ secrets.MERGE_BUMP_BRANCH_TOKEN }}
        MERGE_METHOD: REBASE

