# PR workflow.
#
# Runs full suite of checks, with warnings treated as errors.
# Gather code coverage stats and publish them on coveralls.io.

name: Merge Version Change PRs automatically

on: pull_request

jobs:
  merge:
    runs-on: ubuntu-20.04
    if: "startsWith(github.event.head_commit.message, 'chore(release):')"
    steps:
    - name: Merge Version change PR
      uses: ridedott/merge-me-action@81667e6ae186ddbe6d3c3186d27d91afa7475e2c 
      with:
        GITHUB_LOGIN: MaidSafe-QA
        GITHUB_TOKEN: ${{ secrets.MERGE_BUMP_BRANCH_TOKEN }}
        MERGE_METHOD: REBASE
    # TODO: enable when we want dependabot (it's the default user for this action)
    # - name: Dependabot Merge
    #   uses: ridedott/merge-me-action@master
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.MERGE_BUMP_BRANCH_TOKEN }}
    #     MERGE_METHOD: REBASE

